name: rx_shared_preference
description: Shared preference with RxDart Stream observation. Reactive shared preferences for Flutter
version: 0.0.9
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/rx_shared_preference.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.2
  rxdart: ^0.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
