name: rx_shared_preference
description: This package is now named [rx_shared_preferences](https://pub.dartlang.org/packages/rx_shared_preferences). Please use new name package.
version: 1.0.3+1
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/rx_shared_preference.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  rxdart: ^0.22.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_api: ^0.2.4
flutter:
